### ISSUE TITLE
Add option to let users decide if ambiguous width characters should be 1 or 2 in width

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/string-width#1]
See: https://github.com/twada/power-assert-runtime/pull/14#issuecomment-230982557

**Comment by Offirmo** [comment]
I think I will add that by allowing to provide a custom char width counter

**Comment by be5invis** [comment]
Per my knowledge, at least on Windows, the CONHOST **really measures** the actual width of ambiguous characters in the font the user set.
