### ISSUE TITLE
xo has given up support for Node v4

### ISSUE THREAD

**Issue by tonytonyjan** [sindresorhus/string-width#18]
The following code will make CI environment inconsistent:

https://github.com/sindresorhus/string-width/blob/74d8d552b465692790c41169b123409669d41079/package.json#L51-L54

For instance, xo has dropped support for Node v4 a few months ago (xojs/xo@d1eb47c8984bd0c53d05c7dce4ed7e03b405aa03), and it broke PR #17.

Some suggestions:

* Give up node v4, and add package-locks or yarn.lock to make dependency tree consistent.
* Define xo version in package.json explicitly, for example, use `"0.20.0"`, instead of using `"*"`.

**Comment by sindresorhus** [comment]
Fixed
