### ISSUE TITLE
Breaking change in v2.1

### ISSUE THREAD

**Issue by ljharb** [sindresorhus/string-width#26]
v2.0 of this package depends on `strip-ansi` v3, which supports node v0.10, which works fine with string-width's support of `>= 4`.

however, v2.1 of this package depends on `strip-ansi` v4, which requires `>= 8`, which means it's a breaking change in a minor version of this package. This breaks https://npmjs.com/salita, and every other package that depends on yargs 10.

Please release a v2 version of `string-width` that restores node 4 compatibility. The easiest is probably to revert `strip-ansi` to v3. (The most reliable would be a change in policy in ensuring that every dep supports as far back as is possible, but i realize that's not likely to happen)

**Comment by sindresorhus** [comment]
v2.0.0 of this package required Node.js 4: https://github.com/sindresorhus/string-width/blob/v2.0.0/package.json#L13

---

> however, v2.1 of this package depends on strip-ansi v4, which requires >= 8

No, `strip-ansi` v4 also required Node.js 4: https://github.com/chalk/strip-ansi/blob/v4.0.0/package.json#L13

**Comment by ljharb** [comment]
hmm - i did a bunch of `npm show` commands to come up with these ranges; i'll verify.

**Comment by ljharb** [comment]
Clearly I messed up somewhere - and it may have been complicated by cli-table's similar bug. Everything seems to work now in v4.0 and v4.x, with https://github.com/tbranyen/salita/commit/4c6108fb8530022a8ab41a8a90bab3a6cfccdf00 reverted.

Sorry for the noise!
