### ISSUE TITLE
👋  Hello from varsize-string!

### ISSUE THREAD

**Issue by martinheidegger** [sindresorhus/string-width#3]
Hi there, I have been working on a similar project: https://github.com/martinheidegger/varsize-string It is used at NodeSchool to implement internationalisation for cli tools with https://github.com/martinheidegger/wcstring I thought the problems solved are similar, maybe we can support each other?! cheers!

**Comment by sindresorhus** [comment]
I totally missed this issue... I would be interested in collaborating, but it doesn't look like your modules are maintained anymore.

**Comment by martinheidegger** [comment]
It doesn't look like it, but I am available for collaboration still. How would you like them to be upgraded. :wave:
