### ISSUE TITLE
Update strip-ansi in 4.2 to address CVE

### ISSUE THREAD

**Issue by woehr** [sindresorhus/string-width#32]
Now that strip-ansi has version 6.0.1 that addresses the CVE in its dependency of ansi-regex (https://github.com/chalk/strip-ansi/issues/40; thank you!), would it be possible to update the strip-ansi dependency in version 4.2 of string-width. This is required for upstream packages that can't update to version 5 due to it being pure ESM.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/string-width/releases/tag/v4.2.3

In the future, you can just add the `ansi-regex`, for example, as a dependency to be able to force a specific version.
