### ISSUE TITLE
Can't require package in Node v14

### ISSUE THREAD

**Issue by JoshuaWise** [sindresorhus/string-width#33]
I'm trying to `require` this package in my project, but I'm getting this error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /project/node_modules/string-width/index.js
require() of ES modules is not supported.
require() of /project/node_modules/string-width/index.js from /project/lib/printer.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /project/node_modules/string-width/package.json
```

It seems like my only option is to convert my entire project into ES modules, which is not possible given my current situation. How can I use this package from a standard Node project?

**Comment by JoshuaWise** [comment]
Nevermind, I see that I can use version `4.2.3`.

**Comment by ks221197** [comment]
@JoshuaWise hello, my application made with nuxtjs 2.x.x and i don't individually installed string-width package but still getting this error on pm2 start.
please check this out,
https://stackoverflow.com/questions/72741097/error-err-require-esm-in-nuxtjs-2-while-deploying-with-ec2?noredirect=1#comment128487643_72741097
