### ISSUE TITLE
can not import in node environment

### ISSUE THREAD

**Issue by LynnHg** [sindresorhus/string-width#44]
Thank you for your nice work.

When I use
`import stringWidth from 'string-width';`
I got an Error [ERR_REQUIRE_ESM]: Must use import to load ES Module.

Hope to support this way to import at the same time:
`const stringWidth = require('string-width');`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by LynnHg** [comment]
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

Tanks for your great help!

**Comment by glassdimlygr** [comment]
A great way to make your module irrelevant, by converting it to pure ESM. Currently, `string-width` is making my build of `canvas` fail.
