### ISSUE TITLE
Usage of Intl.Segmenter() breaks on Firefox

### ISSUE THREAD

**Issue by outloudvi** [sindresorhus/string-width#50]
3 weeks ago, #47 introduced `Intl.Segmenter()`. However, since [it's not supported by Firefox](https://caniuse.com/mdn-javascript_builtins_intl_segmenter_segmenter), this will break sites using `string-width@^6.0.0` ([approx. 1500 installs](https://www.npmjs.com/package/string-width?activeTab=versions)).

For a real-world example, the error is shown as below when I visited [this site](https://pyonpyon.today) over Firefox Nightly 115.0a1:
![Error on Firefox](https://github.com/sindresorhus/string-width/assets/19144373/12f62b76-a2c2-447d-b133-e4ef1380a1b0)

**Comment by sindresorhus** [comment]
I have noted it in the release notes. I have no intention of working around lack of support for this in Firefox though.

https://github.com/sindresorhus/string-width/releases/tag/v6.0.0

**Comment by outloudvi** [comment]
Got it. Thanks for your quick reply. :)
