### ISSUE TITLE
Incomplete support for XTerm escape codes

### ISSUE THREAD

**Issue by jepler** [sindresorhus/string-width#7]
Many Unix terminals follow "XTerm escape codes".  I refer to the "rxvt_reference" manpage, available on Debian Jessie as `man 7 urxvt` when the `rxvt-unicode` package is installed:

~~~~
   XTerm Operating System Commands
       "ESC ] Ps;Pt ST"
           Set XTerm Parameters. 8-bit ST: 0x9c, 7-bit ST sequence: ESC \
           (0x1b, 0x5c), backwards compatible terminator BEL (0x07) is also
           accepted. any octet can be escaped by prefixing it with SYN (0x16,
           ^V).

           Ps = 0     Change Icon Name and Window Title to Pt
           Ps = 1     Change Icon Name to Pt
           Ps = 2     Change Window Title to Pt
...
~~~~

So, for example, the sequence `\033]2;example\007` will change the terminal's title to "example" and not use any of the character cells in the terminal itself.

This could be represented as a (non-passing) test:
~~~~
t.is(m('\033]2;example\007'), 0)
~~~~
and similar for the ST sequences '\033\\' and '\x9c' though to be honest I'm not sure whether the 8-bit '\x9c' even makes sense in UTF-8 world or can be expressed in javascript unicode strings.since it is only valid as a continuation byte in the UTF-8 encoding; it can probably be ignored.

**Comment by sindresorhus** [comment]
Can you move this over to https://github.com/chalk/strip-ansi ? It's the module stripping the ansi codes before measuring.
